SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM FISH_INFO I
JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
WHERE I.LENGTH = (SELECT MAX(CASE WHEN LENGTH IS NULL THEN 10 ELSE LENGTH END) 
                  FROM FISH_INFO 
                  WHERE FISH_TYPE = I.FISH_TYPE)
ORDER BY I.ID;
